/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-30-g5935269

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: master.xdd
        File Version: 1

        Created:      2023/10/28 1:11:24
        Created By:   
        Modified:     2025/2/18 10:57:20
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: STM32Master
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 7
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 9


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1404_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1405_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1406_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1604_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1605_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1606_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint32_t x2000_user_save;
    uint32_t x2001_user_setting;
    uint32_t x2002_factory_setting;
    uint32_t x2003_temp_board;
    uint32_t x2004_temp_motor;
    uint32_t x2005_argu_1;
    uint32_t x2006_motor_ID;
    uint32_t x2007_baud_rate;
    uint32_t x2008_position_deviation;
    uint32_t x2009_max_current;
    uint32_t x200A_min_current;
    uint32_t x200B_absolut_current;
    uint32_t x200C_current_Temp_motor;
    uint32_t x200D_current_Temp_board;
    uint32_t x200E_current_voltage;
    uint32_t x20FF_programVersion;
    uint32_t x6007_communicateProtect;
    uint32_t x603F_errorState;
    uint32_t x6040_controlData;
    uint32_t x6041_statusData;
    uint32_t x6060_operationMode;
    uint32_t x6061_revealMode;
    uint32_t x6062_userPositionOrder;
    uint32_t x6063_motorPositionFeedback;
    uint32_t x6064_userPositionFeedback;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t ID16064;
        uint32_t ID26064;
        uint32_t ID36064;
        uint32_t ID46064;
        uint32_t ID56064;
        uint32_t ID66064;
        uint32_t ID76064;
    } x6065__6064;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t ID4607A;
        uint32_t ID5607A;
        uint32_t ID6607A;
        uint32_t ID7607A;
    } x6066__607A;
    uint32_t x606C_userSpeedFeedback;
    uint32_t x606D_speedThresholdWindow;
    uint32_t x606E_speedThresholdTimeWindow;
    uint32_t x606F_zeroSpeedThreshold;
    uint32_t x6070_zeroSpeedThresholdTime;
    uint32_t x6071_targetTorque;
    uint32_t x6072_maximumTorque;
    uint32_t x6073_maximumOperatingCurrent;
    uint32_t x6074_torqueDemand;
    uint32_t x6075_ratedCurrent;
    uint32_t x6076_ratedTorque;
    uint32_t x6077_torque;
    uint32_t x6078_current;
    uint32_t x6079_voltage;
    uint32_t x607A_target_position;
    uint32_t x607B_position_limit;
    uint32_t x607D_position_limit;
    uint32_t x607F_maxProfileVelocity;
    uint32_t x6080_max_speed;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_contourAcceleration;
    uint32_t x6084_contourDeceleration;
    uint32_t x6087_torqueSlope;
    uint32_t x60F6_current_PID;
    uint32_t x60F9_speed_PID;
    uint32_t x60FB_position_PID;
    uint32_t x60FF_target_speed;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1010 &OD->list[6]
#define OD_ENTRY_H1011 &OD->list[7]
#define OD_ENTRY_H1012 &OD->list[8]
#define OD_ENTRY_H1014 &OD->list[9]
#define OD_ENTRY_H1015 &OD->list[10]
#define OD_ENTRY_H1016 &OD->list[11]
#define OD_ENTRY_H1017 &OD->list[12]
#define OD_ENTRY_H1018 &OD->list[13]
#define OD_ENTRY_H1019 &OD->list[14]
#define OD_ENTRY_H1200 &OD->list[15]
#define OD_ENTRY_H1280 &OD->list[16]
#define OD_ENTRY_H1400 &OD->list[17]
#define OD_ENTRY_H1401 &OD->list[18]
#define OD_ENTRY_H1402 &OD->list[19]
#define OD_ENTRY_H1403 &OD->list[20]
#define OD_ENTRY_H1404 &OD->list[21]
#define OD_ENTRY_H1405 &OD->list[22]
#define OD_ENTRY_H1406 &OD->list[23]
#define OD_ENTRY_H1600 &OD->list[24]
#define OD_ENTRY_H1601 &OD->list[25]
#define OD_ENTRY_H1602 &OD->list[26]
#define OD_ENTRY_H1603 &OD->list[27]
#define OD_ENTRY_H1604 &OD->list[28]
#define OD_ENTRY_H1605 &OD->list[29]
#define OD_ENTRY_H1606 &OD->list[30]
#define OD_ENTRY_H1800 &OD->list[31]
#define OD_ENTRY_H1801 &OD->list[32]
#define OD_ENTRY_H1802 &OD->list[33]
#define OD_ENTRY_H1803 &OD->list[34]
#define OD_ENTRY_H1A00 &OD->list[35]
#define OD_ENTRY_H1A01 &OD->list[36]
#define OD_ENTRY_H1A02 &OD->list[37]
#define OD_ENTRY_H1A03 &OD->list[38]
#define OD_ENTRY_H2000 &OD->list[39]
#define OD_ENTRY_H2001 &OD->list[40]
#define OD_ENTRY_H2002 &OD->list[41]
#define OD_ENTRY_H2003 &OD->list[42]
#define OD_ENTRY_H2004 &OD->list[43]
#define OD_ENTRY_H2005 &OD->list[44]
#define OD_ENTRY_H2006 &OD->list[45]
#define OD_ENTRY_H2007 &OD->list[46]
#define OD_ENTRY_H2008 &OD->list[47]
#define OD_ENTRY_H2009 &OD->list[48]
#define OD_ENTRY_H200A &OD->list[49]
#define OD_ENTRY_H200B &OD->list[50]
#define OD_ENTRY_H200C &OD->list[51]
#define OD_ENTRY_H200D &OD->list[52]
#define OD_ENTRY_H200E &OD->list[53]
#define OD_ENTRY_H20FF &OD->list[54]
#define OD_ENTRY_H6007 &OD->list[55]
#define OD_ENTRY_H603F &OD->list[56]
#define OD_ENTRY_H6040 &OD->list[57]
#define OD_ENTRY_H6041 &OD->list[58]
#define OD_ENTRY_H6060 &OD->list[59]
#define OD_ENTRY_H6061 &OD->list[60]
#define OD_ENTRY_H6062 &OD->list[61]
#define OD_ENTRY_H6063 &OD->list[62]
#define OD_ENTRY_H6064 &OD->list[63]
#define OD_ENTRY_H6065 &OD->list[64]
#define OD_ENTRY_H6066 &OD->list[65]
#define OD_ENTRY_H606C &OD->list[66]
#define OD_ENTRY_H606D &OD->list[67]
#define OD_ENTRY_H606E &OD->list[68]
#define OD_ENTRY_H606F &OD->list[69]
#define OD_ENTRY_H6070 &OD->list[70]
#define OD_ENTRY_H6071 &OD->list[71]
#define OD_ENTRY_H6072 &OD->list[72]
#define OD_ENTRY_H6073 &OD->list[73]
#define OD_ENTRY_H6074 &OD->list[74]
#define OD_ENTRY_H6075 &OD->list[75]
#define OD_ENTRY_H6076 &OD->list[76]
#define OD_ENTRY_H6077 &OD->list[77]
#define OD_ENTRY_H6078 &OD->list[78]
#define OD_ENTRY_H6079 &OD->list[79]
#define OD_ENTRY_H607A &OD->list[80]
#define OD_ENTRY_H607B &OD->list[81]
#define OD_ENTRY_H607D &OD->list[82]
#define OD_ENTRY_H607F &OD->list[83]
#define OD_ENTRY_H6080 &OD->list[84]
#define OD_ENTRY_H6081 &OD->list[85]
#define OD_ENTRY_H6083 &OD->list[86]
#define OD_ENTRY_H6084 &OD->list[87]
#define OD_ENTRY_H6087 &OD->list[88]
#define OD_ENTRY_H60F6 &OD->list[89]
#define OD_ENTRY_H60F9 &OD->list[90]
#define OD_ENTRY_H60FB &OD->list[91]
#define OD_ENTRY_H60FF &OD->list[92]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H1010_storeParameters &OD->list[6]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[7]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[8]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[9]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[10]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[11]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[12]
#define OD_ENTRY_H1018_identity &OD->list[13]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[14]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[15]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[16]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[18]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1404_RPDOCommunicationParameter &OD->list[21]
#define OD_ENTRY_H1405_RPDOCommunicationParameter &OD->list[22]
#define OD_ENTRY_H1406_RPDOCommunicationParameter &OD->list[23]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[24]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[25]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[26]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[27]
#define OD_ENTRY_H1604_RPDOMappingParameter &OD->list[28]
#define OD_ENTRY_H1605_RPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1606_RPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[31]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[32]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[33]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[34]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[35]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[36]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[37]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[38]
#define OD_ENTRY_H2000_user_save &OD->list[39]
#define OD_ENTRY_H2001_user_setting &OD->list[40]
#define OD_ENTRY_H2002_factory_setting &OD->list[41]
#define OD_ENTRY_H2003_temp_board &OD->list[42]
#define OD_ENTRY_H2004_temp_motor &OD->list[43]
#define OD_ENTRY_H2005_argu_1 &OD->list[44]
#define OD_ENTRY_H2006_motor_ID &OD->list[45]
#define OD_ENTRY_H2007_baud_rate &OD->list[46]
#define OD_ENTRY_H2008_position_deviation &OD->list[47]
#define OD_ENTRY_H2009_max_current &OD->list[48]
#define OD_ENTRY_H200A_min_current &OD->list[49]
#define OD_ENTRY_H200B_absolut_current &OD->list[50]
#define OD_ENTRY_H200C_current_Temp_motor &OD->list[51]
#define OD_ENTRY_H200D_current_Temp_board &OD->list[52]
#define OD_ENTRY_H200E_current_voltage &OD->list[53]
#define OD_ENTRY_H20FF_programVersion &OD->list[54]
#define OD_ENTRY_H6007_communicateProtect &OD->list[55]
#define OD_ENTRY_H603F_errorState &OD->list[56]
#define OD_ENTRY_H6040_controlData &OD->list[57]
#define OD_ENTRY_H6041_statusData &OD->list[58]
#define OD_ENTRY_H6060_operationMode &OD->list[59]
#define OD_ENTRY_H6061_revealMode &OD->list[60]
#define OD_ENTRY_H6062_userPositionOrder &OD->list[61]
#define OD_ENTRY_H6063_motorPositionFeedback &OD->list[62]
#define OD_ENTRY_H6064_userPositionFeedback &OD->list[63]
#define OD_ENTRY_H6065__6064 &OD->list[64]
#define OD_ENTRY_H6066__607A &OD->list[65]
#define OD_ENTRY_H606C_userSpeedFeedback &OD->list[66]
#define OD_ENTRY_H606D_speedThresholdWindow &OD->list[67]
#define OD_ENTRY_H606E_speedThresholdTimeWindow &OD->list[68]
#define OD_ENTRY_H606F_zeroSpeedThreshold &OD->list[69]
#define OD_ENTRY_H6070_zeroSpeedThresholdTime &OD->list[70]
#define OD_ENTRY_H6071_targetTorque &OD->list[71]
#define OD_ENTRY_H6072_maximumTorque &OD->list[72]
#define OD_ENTRY_H6073_maximumOperatingCurrent &OD->list[73]
#define OD_ENTRY_H6074_torqueDemand &OD->list[74]
#define OD_ENTRY_H6075_ratedCurrent &OD->list[75]
#define OD_ENTRY_H6076_ratedTorque &OD->list[76]
#define OD_ENTRY_H6077_torque &OD->list[77]
#define OD_ENTRY_H6078_current &OD->list[78]
#define OD_ENTRY_H6079_voltage &OD->list[79]
#define OD_ENTRY_H607A_target_position &OD->list[80]
#define OD_ENTRY_H607B_position_limit &OD->list[81]
#define OD_ENTRY_H607D_position_limit &OD->list[82]
#define OD_ENTRY_H607F_maxProfileVelocity &OD->list[83]
#define OD_ENTRY_H6080_max_speed &OD->list[84]
#define OD_ENTRY_H6081_profileVelocity &OD->list[85]
#define OD_ENTRY_H6083_contourAcceleration &OD->list[86]
#define OD_ENTRY_H6084_contourDeceleration &OD->list[87]
#define OD_ENTRY_H6087_torqueSlope &OD->list[88]
#define OD_ENTRY_H60F6_current_PID &OD->list[89]
#define OD_ENTRY_H60F9_speed_PID &OD->list[90]
#define OD_ENTRY_H60FB_position_PID &OD->list[91]
#define OD_ENTRY_H60FF_target_speed &OD->list[92]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
